name: Lab 2 - CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  echo-message:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo message
        run: echo "Hi, I am from COSC 1209 class"

  build-and-deploy:
    needs: echo-message
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Build Docker image 
      run: docker build -t kulwinder013/java-app-with-gradle:${{ github.sha }} .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: docker push kulwinder013/java-app-with-gradle:${{ github.sha }}

